autoinstall:
  version: 1
  refresh-installer:
    update: true
    channel: latest/edge
  source:
    search_drivers: true
    id: ubuntu-desktop
  identity:
    realname: 'Michael Nutt'
    username: michael-nutt
    password: '$y$j9T$7y/VEgA0LdU8uXB5OUwIs/$goxysJlLfRhG1mABwzX8OE9bdjYuvv4r9EmYVDFoDE9'
    hostname: framework-o-doom
  drivers:
    install: true
  packages:
    - vim
    - git
    - net-tools
  timezone: "America/Chicago"
  updates: all
  late-commands:
    - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
    - sudo apt-get install wget gpg
    - wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
    - sudo install -D -o root -g root -m 644 microsoft.gpg /usr/share/keyrings/microsoft.gpg
    - rm -f microsoft.gpg
    - 
