autoinstall:
  version: 1
  interactive-sections:
    - network
    - storage
  identity:
    realname: 'Michael Nutt'
    username: michael-nutt
    password: '$y$j9T$7y/VEgA0LdU8uXB5OUwIs/$goxysJlLfRhG1mABwzX8OE9bdjYuvv4r9EmYVDFoDE9'
    hostname: framework-o-doom
  keyboard:
    layout: us
  locale: en_US.UTF-8
# --- Packages and Late Commands ---
# Standard Packages
  packages:
    - cmake
    - curl
    - g++
    - git
    - net-tools
    - python3-netifaces
    - rename
    - vim
    - whois
# Late Commands
  late-commands:
    # Home dir path
    - USER_HOME="/target/home/michael-nutt"

    # --- Download Dotfiles ---
    - wget $USER_HOME/.bash_aliases "https://github.com/michaelnutt2/ComputerConfig/raw/refs/heads/trunk/dots/.bash_aliases"
    - wget $USER_HOME/.bashrc "https://github.com/michaelnutt2/ComputerConfig/raw/refs/heads/trunk/dots/.bashrc"
    - wget $USER_HOME/.gitconfig "https://github.com/michaelnutt2/ComputerConfig/raw/refs/heads/trunk/dots/.gitconfig"
    - wget $USER_HOME/.myprompt.bash "https://github.com/michaelnutt2/ComputerConfig/raw/refs/heads/trunk/dots/.myprompt.bash"
    - wget $USER_HOME/.vimrc "https://github.com/michaelnutt2/ComputerConfig/raw/refs/heads/trunk/dots/.vimrc"

    # Set correct ownership/permissions
    - chown 1000:1000 $USER_HOME/.bash_aliases
    - chown 1000:1000 $USER_HOME/.bashrc
    - chown 1000:1000 $USER_HOME/.gitconfig
    - chown 1000:1000 $USER_HOME/.myprompt.bash
    - chown 1000:1000 $USER_HOME/.vimrc

    # --- Add Repos for Other Apps ---

    # Wireshark
    - curtin in-target -- add-apt-repository -y ppa:wireshark-dev/stable

    # GH CLI
    - mkdir -p -m 755 /target/etc/apt/keyrings
    - wget https://cli.github.com/packages/githubcli-archive-keyring.gpg -O /target/etc/apt/keyrings/githubcli-archive-keyring.gpg
    - chmod go+r /target/etc/apt/keyrings/githubcli-archive-keyring.gpg
    - curtin in-target -- sh -c 'echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" > /etc/apt/sources.list.d/github-cli.list'

    # VS Code
    - wget 'https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-x64' -O /target/tmp/vscode_latest.deb
    - curtin in-target -- sh -c 'echo "code code/add-microsoft-repo boolean true" | debconf-set-selections'
    - curtin in-target -- sh -c 'apt install ./tmp/vscode_latest.deb -y'
    - rm /target/tmp/vscode_latest.deb

    # Obsidian
    - wget 'https://github.com/obsidianmd/obsidian-releases/releases/download/v1.9.14/obsidian_1.9.14_amd64.deb' -O /target/tmp/obsidian_latest.deb
    - curtin in-target -- apt install ./tmp/obsidian_latest.deb -y
    - rm /target/tmp/obsidian_latest.deb

    # Steam
    - wget 'https://cdn.fastly.steamstatic.com/client/installer/steam.deb' -O /target/tmp/steam_latest.deb
    - curtin in-target -- apt install ./tmp/steam_latest.deb -y
    - rm /target/tmp/steam_latest.deb

    # --- Install Other Apps ---
    - curtin in-target -- apt-get update
    - curtin in-target -- apt-get install -y wireshark gh
    - curtin in-target -- apt-get upgrade -y