autoinstall:
  version: 1
  interactive-sections:
    - network
  identity:
    realname: 'Michael Nutt'
    username: michael-nutt
    password: '$y$j9T$7y/VEgA0LdU8uXB5OUwIs/$goxysJlLfRhG1mABwzX8OE9bdjYuvv4r9EmYVDFoDE9'
    hostname: framework-o-doom
  keyboard:
    layout: us
  locale: en_US.UTF-8
  storage:
    layout:
      name: lvm
# --- Packages and Late Commands ---
# Standard Packages
  packages:
    - cmake
    - curl
    - g++
    - git
    - net-tools
    - python3-netifaces
    - rename
    - vim
    - whois
# Late Commands
  late-commands:
    # Home dir path
    - USER_HOME="/target/home/michael-nutt"

    # --- Download Dotfiles ---
    - curl -L -o $USER_HOME/.bash_aliases "https://github.com/michaelnutt2/ComputerConfig/raw/refs/heads/trunk/dots/.bash_aliases"
    - curl -L -o $USER_HOME/.bashrc "https://github.com/michaelnutt2/ComputerConfig/raw/refs/heads/trunk/dots/.bashrc"
    - curl -L -o $USER_HOME/.gitconfig "https://github.com/michaelnutt2/ComputerConfig/raw/refs/heads/trunk/dots/.gitconfig"
    - curl -L -o $USER_HOME/.myprompt.bash "https://github.com/michaelnutt2/ComputerConfig/raw/refs/heads/trunk/dots/.myprompt.bash"
    - curl -L -o $USER_HOME/.vimrc "https://github.com/michaelnutt2/ComputerConfig/raw/refs/heads/trunk/dots/.vimrc"

    # Set correct ownership/permissions
    - chown 1000:1000 $USER_HOME/.bash_aliases
    - chown 1000:1000 $USER_HOME/.bashrc
    - chown 1000:1000 $USER_HOME/.gitconfig
    - chown 1000:1000 $USER_HOME/.myprompt.bash
    - chown 1000:1000 $USER_HOME/.vimrc
